version: "2.4"

services:

  build:
    image: klakegg/hugo:0.55.1
    environment:
      - HUGO_DESTINATION=/public_html
    volumes:
      - ".:/src"
      - "./public_html:/public_html"

  server:
    image: klakegg/hugo:0.55.1
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
